site_name: Homelab Infra Portfolio CICD
site_url: https://dawo9889.github.io/My-Portfolio-CICD-2.0
repo_url: https://github.com/Dawo9889/My-Portfolio-CICD-2.0
repo_name: GitHub
theme:
  name: material
  features:
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: indigo
      accent: blue
  language: en
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
plugins:
  - search
nav:
  - Home: index.md
  - Infrastructure:
    - MinIO: infrastructure/minio/setup.md
    - Infisical: infrastructure/infisical/setup.md
    - OpenTofu: infrastructure/tofu/setup.md
