---
- name: Deploy Docker app on remote server
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker Service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull and run Docker container
      community.docker.docker_container:
        name: portfolio-cicd
        image: {{ image | default('ghcr.io/dawo9889/my-portfolio-cicd-2.0:latest') }}
        state: started
        restart_policy: always
        published_ports:
          - "3000:3000"
        pull: true
