name: Deploy to Production (orchestrator)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

  terraform:
    uses: ./.github/workflows/reusable-tofu.yml

  deploy:
    needs: [build, terraform]
    uses: ./.github/workflows/reusable-ansible.yml
    with:
      image: ${{ needs.build.outputs.image }}