name: PR CI — lint, build, image smoke

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install app dependencies
        run: npm ci --no-audit --no-fund
        working-directory: ./app

      - name: Run linter
        run: npm run lint
        working-directory: ./app

      - name: Build Next.js app
        run: npm run build
        working-directory: ./app

      - name: Build Docker image for testing
        run: |
          docker build --progress=plain -t my-portfolio-test:${{ github.sha }} .

      - name: Run Docker container
        run: |
          docker run -d --name my-portfolio-test -p 3000:3000 my-portfolio-test:${{ github.sha }}
          # wait for the app to become available (max ~60s)
          for i in {1..30}; do
            if curl -sS http://localhost:3000/ > /dev/null; then
              echo "server is up"
              break
            fi
            sleep 2
          done
        shell: bash

      - name: Smoke test (HTTP 200)
        run: |
          curl -fS http://localhost:3000/ || (echo "Smoke test failed, container logs:" && docker logs my-portfolio-test && exit 1)

      - name: Cleanup container
        if: always()
        run: docker rm -f my-portfolio-test || true
