name: test Infisical integration
on:
  workflow_dispatch:

jobs:
  test-infisical:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Debug OIDC Claims
        uses: steve-todorov/oidc-debugger-action@v1
        with:
          audience: '${{ github.server_url }}/${{ github.repository }}'

      - uses: Infisical/secrets-action@v1.0.7
        with:
          domain: "https://infisical.dawo9889-homelab.ovh"
          method: "oidc"
          env-slug: "prod"
          project-slug: "portfolio-cicd-r-shw"
          identity-id: "5889a899-c926-4e4d-aed7-a6af89855305"
          secret-path: "/tofu"

      # - name: Test ssh script
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: 192.168.1.16
      #     username: ubuntu
      #     key: ${{ secrets.PORTFOLIO_CICD_SSH_KEY }}
      #     script: |
      #       ip a