name: test Infisical integration
on:
  workflow_dispatch:

jobs:
  test-infisical:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Debug OIDC Claims
        uses: steve-todorov/oidc-debugger-action@v1
        with:
          audience: '${{ github.server_url }}/${{ github.repository }}'

      - uses: Infisical/secrets-action@v1.0.7
        with:
            domain: "https://infisical.dawo9889-homelab.ovh"
            method: "oidc"
            env-slug: "dev"
            project-slug: "portfolio-cicd-l1g-g"
            identity-id: "e2c4d1b8-7a5d-4fed-96c9-a3a71369cf4c"